name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-node-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-backend-

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Check TypeScript compile errors
        working-directory: ./backend
        run: npm run build

      - name: Run ESLint
        working-directory: ./backend
        run: npm run lint

      - name: Run tests
        working-directory: ./backend
        run: npm test

      - name: Generate test coverage report
        working-directory: ./backend
        run: npm run coverage
